/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void guiDraw(PApplet appc, GWinData data) { //_CODE_:gui:962177:
  appc.background(230);
} //_CODE_:gui:962177:

public void changeSize(GCustomSlider source, GEvent event) { //_CODE_:sizeSlider:231715:
  
} //_CODE_:sizeSlider:231715:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  gui = GWindow.getWindow(this, "GUI", 0, 0, 240, 120, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "guiDraw");
  sizeSlider = new GCustomSlider(gui, 70, 40, 100, 40, "grey_blue");
  sizeSlider.setShowValue(true);
  sizeSlider.setLimits(2.0, 1.0, 4.0);
  sizeSlider.setNumberFormat(G4P.DECIMAL, 2);
  sizeSlider.setOpaque(false);
  sizeSlider.addEventHandler(this, "changeSize");
  gui.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GCustomSlider sizeSlider; 
