/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void guiDraw(PApplet appc, GWinData data) { //_CODE_:gui:962177:
  appc.background(230);
} //_CODE_:gui:962177:

public void changeSize(GCustomSlider source, GEvent event) { //_CODE_:sizeSlider:231715:
  
} //_CODE_:sizeSlider:231715:

public void numParticleChange(GCustomSlider source, GEvent event) { //_CODE_:numParticleSlider:981033:

} //_CODE_:numParticleSlider:981033:

public void randomColClicked(GOption source, GEvent event) { //_CODE_:randomCol:970990:
  chooseColPanel.setCollapsed(true);
} //_CODE_:randomCol:970990:

public void chooseColClicked(GOption source, GEvent event) { //_CODE_:chooseCol:812704:
  chooseColPanel.setCollapsed(false);
} //_CODE_:chooseCol:812704:

public void chooseColPanelClicked(GPanel source, GEvent event) { //_CODE_:chooseColPanel:924436:
  println("chooseColPanel - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:chooseColPanel:924436:

public void knob1_turn1(GKnob source, GEvent event) { //_CODE_:hueKnob:633906:
  println("knob1 - GKnob >> GEvent." + event + " @ " + millis());
} //_CODE_:hueKnob:633906:

public void saturationSliderTurned(GCustomSlider source, GEvent event) { //_CODE_:saturationSlider:872026:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:saturationSlider:872026:

public void brightnessSliderClicked(GCustomSlider source, GEvent event) { //_CODE_:brightnessSlider:726275:
  println("custom_slider2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:brightnessSlider:726275:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  gui = GWindow.getWindow(this, "GUI", 0, 0, 360, 240, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "guiDraw");
  sizeSlider = new GCustomSlider(gui, 70, 40, 100, 40, "grey_blue");
  sizeSlider.setShowValue(true);
  sizeSlider.setLimits(2.0, 1.0, 4.0);
  sizeSlider.setNumberFormat(G4P.DECIMAL, 2);
  sizeSlider.setOpaque(false);
  sizeSlider.addEventHandler(this, "changeSize");
  sizeLabel = new GLabel(gui, 3, 47, 69, 20);
  sizeLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  sizeLabel.setText("Particle Size");
  sizeLabel.setOpaque(false);
  numParticleLabel = new GLabel(gui, 11, 98, 49, 19);
  numParticleLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  numParticleLabel.setText("NumberParticle");
  numParticleLabel.setOpaque(false);
  numParticleSlider = new GCustomSlider(gui, 70, 90, 100, 40, "grey_blue");
  numParticleSlider.setShowValue(true);
  numParticleSlider.setLimits(100, 0, 200);
  numParticleSlider.setNumberFormat(G4P.INTEGER, 0);
  numParticleSlider.setOpaque(false);
  numParticleSlider.addEventHandler(this, "numParticleChange");
  colorFirework = new GToggleGroup();
  randomCol = new GOption(gui, 200, 50, 120, 20);
  randomCol.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  randomCol.setText("random color");
  randomCol.setOpaque(false);
  randomCol.addEventHandler(this, "randomColClicked");
  chooseCol = new GOption(gui, 200, 80, 120, 20);
  chooseCol.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  chooseCol.setText("choose color");
  chooseCol.setOpaque(false);
  chooseCol.addEventHandler(this, "chooseColClicked");
  colorFirework.addControl(randomCol);
  colorFirework.addControl(chooseCol);
  chooseCol.setSelected(true);
  chooseColPanel = new GPanel(gui, 200, 120, 160, 120, "choose color");
  chooseColPanel.setText("choose color");
  chooseColPanel.setOpaque(true);
  chooseColPanel.addEventHandler(this, "chooseColPanelClicked");
  hueKnob = new GKnob(gui, 0, 40, 60, 60, 1.0);
  hueKnob.setTurnRange(0, 359);
  hueKnob.setTurnMode(GKnob.CTRL_ANGULAR);
  hueKnob.setShowArcOnly(false);
  hueKnob.setOverArcOnly(false);
  hueKnob.setIncludeOverBezel(false);
  hueKnob.setShowTrack(true);
  hueKnob.setLimits(0.5, 0.0, 360.0);
  hueKnob.setShowTicks(true);
  hueKnob.setOpaque(false);
  hueKnob.addEventHandler(this, "knob1_turn1");
  saturationSlider = new GCustomSlider(gui, 110, 30, 90, 40, "grey_blue");
  saturationSlider.setRotation(PI/2, GControlMode.CORNER);
  saturationSlider.setLimits(0.5, 0.0, 100.0);
  saturationSlider.setNumberFormat(G4P.DECIMAL, 2);
  saturationSlider.setOpaque(false);
  saturationSlider.addEventHandler(this, "saturationSliderTurned");
  brightnessSlider = new GCustomSlider(gui, 160, 30, 90, 40, "grey_blue");
  brightnessSlider.setRotation(PI/2, GControlMode.CORNER);
  brightnessSlider.setLimits(0.5, 0.0, 1.0);
  brightnessSlider.setNumberFormat(G4P.DECIMAL, 2);
  brightnessSlider.setOpaque(false);
  brightnessSlider.addEventHandler(this, "brightnessSliderClicked");
  chooseColPanel.addControl(hueKnob);
  chooseColPanel.addControl(saturationSlider);
  chooseColPanel.addControl(brightnessSlider);
  gui.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GCustomSlider sizeSlider; 
GLabel sizeLabel; 
GLabel numParticleLabel; 
GCustomSlider numParticleSlider; 
GToggleGroup colorFirework; 
GOption randomCol; 
GOption chooseCol; 
GPanel chooseColPanel; 
GKnob hueKnob; 
GCustomSlider saturationSlider; 
GCustomSlider brightnessSlider; 
