/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void guiDraw(PApplet appc, GWinData data) { //_CODE_:gui:962177:
  appc.background(230);
} //_CODE_:gui:962177:

public void changeSize(GCustomSlider source, GEvent event) { //_CODE_:sizeSlider:231715:
  
} //_CODE_:sizeSlider:231715:

public void numParticleChange(GCustomSlider source, GEvent event) { //_CODE_:numParticleSlider:981033:

} //_CODE_:numParticleSlider:981033:

public void randomHueClicked(GOption source, GEvent event) { //_CODE_:randomHue:970990:
  chooseHuePanel.setCollapsed(true);
  ranHue = true;
} //_CODE_:randomHue:970990:

public void chooseHueClicked(GOption source, GEvent event) { //_CODE_:chooseHue:812704:
  chooseHuePanel.setCollapsed(false);
  ranHue = false;
} //_CODE_:chooseHue:812704:

public void chooseHuePanelClicked(GPanel source, GEvent event) { //_CODE_:chooseHuePanel:924436:
  println("chooseColPanel - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:chooseHuePanel:924436:

public void hueKnobTurn(GKnob source, GEvent event) { //_CODE_:hueKnob:633906:
  hue = hueKnob.getValueI();
} //_CODE_:hueKnob:633906:

public void shapeDropListClicked(GDropList source, GEvent event) { //_CODE_:shapeDropList:276311:

} //_CODE_:shapeDropList:276311:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  gui = GWindow.getWindow(this, "GUI", 0, 0, 360, 240, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "guiDraw");
  sizeSlider = new GCustomSlider(gui, 70, 10, 100, 40, "grey_blue");
  sizeSlider.setShowValue(true);
  sizeSlider.setLimits(2.0, 1.0, 4.0);
  sizeSlider.setNumberFormat(G4P.DECIMAL, 2);
  sizeSlider.setOpaque(false);
  sizeSlider.addEventHandler(this, "changeSize");
  sizeLabel = new GLabel(gui, 0, 20, 69, 20);
  sizeLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  sizeLabel.setText("Particle Size");
  sizeLabel.setOpaque(false);
  numParticleLabel = new GLabel(gui, 10, 50, 50, 20);
  numParticleLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  numParticleLabel.setText("NumberParticle");
  numParticleLabel.setOpaque(false);
  numParticleSlider = new GCustomSlider(gui, 70, 40, 100, 40, "grey_blue");
  numParticleSlider.setShowValue(true);
  numParticleSlider.setLimits(100, 0, 200);
  numParticleSlider.setNumberFormat(G4P.INTEGER, 0);
  numParticleSlider.setOpaque(false);
  numParticleSlider.addEventHandler(this, "numParticleChange");
  colorFirework = new GToggleGroup();
  randomHue = new GOption(gui, 200, 50, 120, 20);
  randomHue.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  randomHue.setText("random hue");
  randomHue.setOpaque(false);
  randomHue.addEventHandler(this, "randomHueClicked");
  chooseHue = new GOption(gui, 200, 80, 120, 20);
  chooseHue.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  chooseHue.setText("choose hue");
  chooseHue.setOpaque(false);
  chooseHue.addEventHandler(this, "chooseHueClicked");
  colorFirework.addControl(randomHue);
  colorFirework.addControl(chooseHue);
  chooseHue.setSelected(true);
  chooseHuePanel = new GPanel(gui, 200, 120, 120, 90, "choose Hue");
  chooseHuePanel.setText("choose Hue");
  chooseHuePanel.setOpaque(true);
  chooseHuePanel.addEventHandler(this, "chooseHuePanelClicked");
  hueKnob = new GKnob(gui, 0, 20, 60, 60, 1.0);
  hueKnob.setTurnRange(0, 359);
  hueKnob.setTurnMode(GKnob.CTRL_ANGULAR);
  hueKnob.setShowArcOnly(false);
  hueKnob.setOverArcOnly(false);
  hueKnob.setIncludeOverBezel(false);
  hueKnob.setShowTrack(true);
  hueKnob.setLimits(0.5, 0.0, 360.0);
  hueKnob.setShowTicks(true);
  hueKnob.setOpaque(false);
  hueKnob.addEventHandler(this, "hueKnobTurn");
  chooseHuePanel.addControl(hueKnob);
  shapeDropList = new GDropList(gui, 10, 100, 110, 120, 5, 10);
  //shapeDropList.setItems(loadStrings("list_276311"), 0);
  shapeDropList.addEventHandler(this, "shapeDropListClicked");
  gui.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GCustomSlider sizeSlider; 
GLabel sizeLabel; 
GLabel numParticleLabel; 
GCustomSlider numParticleSlider; 
GToggleGroup colorFirework; 
GOption randomHue; 
GOption chooseHue; 
GPanel chooseHuePanel; 
GKnob hueKnob; 
GDropList shapeDropList; 
